### ISSUE TITLE
Llama 2 finetuned models in organization card not found

### ISSUE THREAD

**Issue by Ahmedfrkh** [QinbinLi/LLMPC-Blue#1]
Hi, 

the links for the llama 2 finetuned models models in the organization card (not the models section) lead to 404 not found. Do you plan to release them? Can anyone help fix this issue?

Thanks!

**Comment by QinbinLi** [comment]
Hi @Ahmedfrkh ,

In the competition, we use Llama 3.1 finetuned model [here](https://huggingface.co/LLM-PBE/Llama3.1-8b-instruct-LLMPC-Blue-Team). Please set the`model` parameter as shown in README if running our demo attack. Thanks!

**Comment by Ahmedfrkh** [comment]
Thanks for the quick answer. Do you also plan to release the llama 2 finetuned models models in the organization card here: https://huggingface.co/LLM-PBE ?

**Comment by QinbinLi** [comment]
We have finetuned many models. What llama 2 finetuned models are you referring to?

**Comment by Ahmedfrkh** [comment]
The models below from https://huggingface.co/LLM-PBE :

Organization Card
Model List

Enron dataset

Lora, Llama2-7b
[enron-llama2-7b-undefended](https://huggingface.co/LLM-PBE/enron-llama2-7b-undefended)
[enron-llama2-7b-scrubbed](https://huggingface.co/LLM-PBE/enron-llama2-7b-scrubbed)
[enron-llama2-7b-dp8](https://huggingface.co/LLM-PBE/enron-llama2-7b-dp8)
Lora, Llama2-7b chat
[enron-llama2-7b-chat-undefended](https://huggingface.co/LLM-PBE/enron-llama2-7b-chat-undefended)
[enron-llama2-7b-chat-scrubbed](https://huggingface.co/LLM-PBE/enron-llama2-7b-chat-scrubbed)
[enron-llama2-7b-chat-dp8](https://huggingface.co/LLM-PBE/enron-llama2-7b-chat-dp8)
Full finetuning, llama2-7b
[llama-2-7B-enron-undefended 4epoch](https://huggingface.co/LLM-PBE/together-llama-2-7B-enron-scrubbed/tree/checkpoint_1804)
[llama-2-7B-enron-undefended 10epoch](https://huggingface.co/LLM-PBE/together-llama-2-7B-enron-undefended/tree/checkpoint_4059)
[llama-2-7B-enron-scrubbed 4epoch](https://huggingface.co/LLM-PBE/together-llama-2-7B-enron-scrubbed/tree/checkpoint_1764)
[llama-2-7B-enron-scrubbed 10 epoch](https://huggingface.co/LLM-PBE/together-llama-2-7B-enron-scrubbed/tree/final_model)
Echr dataset

Lora, Llama2-7b
[echr-llama2-7b-undefended](https://huggingface.co/LLM-PBE/echr-llama2-7b-undefended)
[echr-llama2-7b-scrubbed](https://huggingface.co/LLM-PBE/echr-llama2-7b-scrubbed)
[echr-llama2-7b-dp8](https://huggingface.co/LLM-PBE/echr-llama2-7b-dp8)
Lora, Llama2-7b chat
[echr-llama2-7b-chat-undefended](https://huggingface.co/LLM-PBE/echr-llama2-7b-chat-undefended)
[echr-llama2-7b-chat-scrubbed](https://huggingface.co/LLM-PBE/echr-llama2-7b-chat-scrubbed)
[echr-llama2-7b-chat-dp8](https://huggingface.co/LLM-PBE/echr-llama2-7b-chat-dp8)
Full finetuning, llama2-7b
[llama-2-7B-echr-undefended 4epoch](https://huggingface.co/LLM-PBE/together-llama-2-7B-echr-undefended/tree/4epoch)
[llama-2-7B-echr-undefended 10epoch](https://huggingface.co/LLM-PBE/together-llama-2-7B-echr-undefended)
[llama-2-7B-echr-scrubbed 4epoch](https://huggingface.co/LLM-PBE/together-llama-2-7B-echr-scrubbed/tree/checkpoint_184)
[llama-2-7B-echr-scrubbed 10 epoch](https://huggingface.co/LLM-PBE/together-llama-2-7B-echr-scrubbed/tree/final_model)

**Comment by QinbinLi** [comment]
Sorry for the confusion. These models are not related to the competition; they are for testing in another project. Some models may be outdated. We will consider releasing some models with documentation for research purposes in the future.

**Comment by Ahmedfrkh** [comment]
There was no confusion. I am interested in those models for research purposes. It would be very helpful for the research community if you could share them.

Unfortunately, I found out about the competition only after after the registration closed, so I am not participating.

**Comment by QinbinLi** [comment]
I see. We will share some models in the near future. Thanks a lot for your interest!

**Comment by Ahmedfrkh** [comment]
Thanks! I would appreciate if you could let me know here, when you do.

**Comment by QinbinLi** [comment]
Sure. I will close the issue as it is not related to the competition. I'll @ you when the models are released.

**Comment by QinbinLi** [comment]
Hi @Ahmedfrkh ,

FYI, we have released some fine-tuned models. Please refer to the [model list](https://huggingface.co/LLM-PBE).

**Comment by Ahmedfrkh** [comment]
Thank you for sharing!
